services:
  - type: web
    name: virtual-try-on-api
    env: python
    region: oregon  # or choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: RENDER
        value: true 