services:
  - type: web
    name: virtual-tryon-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 